# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  catalogdb:
    image: mongo
  
  basketdb:
    image: postgres
  
  distributedcache:
    image: redis
    
  catalogapi:
    container_name: catalogapi
  
  basketapi:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.Api/Dockerfile
  
  discountapi:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Discount.Api/Dockerfile

volumes:
  mongo_data:
  postrgresdb_basket:  
