# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.
services:
  catalogdb:
    image: mongo
  
  basketdb:
    image: postgres
    
  orderdb:
    image: mcr.microsoft.com/mssql/server

  distributedcache:
    image: redis

  messagebroker:
    image: rabbitmq:3-management

  catalogapi:
    container_name: catalogapi
  
  basketapi:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.Api/Dockerfile
  
  # discountapi:
  #   image: ${DOCKER_REGISTRY-}discountapi
  #   build:
  #     context: .
  #     dockerfile: Discount.Api/Dockerfile

  orderingapi:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Ordering/Ordering.Api/Dockerfile

volumes:
  mongo_data:
  postgresdb_basket:  
